### ISSUE TITLE
can not open PKL document.

### ISSUE THREAD

**Issue by AlexZhangUPUPUP** [climbingdaily/vis_lidar_human_scene#2]
I can not open PKL document.

I can run GUI_Tools.py directly, but can not open PKL document of AMASS dataset.
the link can open here:

https://drive.google.com/drive/folders/1pKp-C7jUtkgCG2X6dO3_6ee0poHqFPX-

The bug is here:

r/SMPL-Scene-Viewer$ python GUI_Tools.py 
FEngine (64 bits) created at 0x558e3345c320 (threading is enabled)
FEngine resolved backend: OpenGL
Loading scene from /home/ubuntu/HumanoidData/SMPL-Scene-Viewer/SMPL-Scene-Viewer/smpl/sample.ply
====> Scene loading comsumed 0.0 s.
[Open3D INFO] [o3d] name: ATUSquat_sync.pkl.
Traceback (most recent call last):
  File "/home/ubuntu/HumanoidData/SMPL-Scene-Viewer/SMPL-Scene-Viewer/gui_vis/human_data.py", line 189, in load
    self.humans = data_loader.load_pkl(filename)
  File "/home/ubuntu/HumanoidData/SMPL-Scene-Viewer/SMPL-Scene-Viewer/util/load_data.py", line 386, in load_pkl
    dets = pkl.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 3: ordinal not in range(128)
Segmentation fault (core dumped)

can you help me to visualize it,thanks

**Comment by climbingdaily** [comment]
Hi, this tool is not compatible with AMASS pkl format because our viewer is intended for dual persons and comparisons with different results for the same person, you can see our format [here](https://github.com/climbingdaily/SMPL-Scene-Viewer/blob/main/gui_vis/readme.md) and [this](https://github.com/climbingdaily/SMPL-Scene-Viewer/blob/main/imgs/smpl_sample.pkl) is our demo pkl file.

But you can easily convert the AMASS PKL to our format with 'pose', 'translation', and 'shape/beta' and set a pkl file as follows:
```
xxx.pkl/
├──'second_person'
|  ├── 'pose'              # list: (N, 72) or (N, 24, 3, 3) 
|  ├── 'mocap_trans' # list: (N, 3), the global translation
|  ├── 'beta'              # list: (10, ) the shape parameters of the SMPL model. 
|  ├── 'gender'          # string: 'male' 'female' 'neutral'. The gender of the SMPL model, default: 'male'
└──'frame_num' # (N, ) 
```

If you have any questions, please contact me with no hesitation.

**Comment by bishnudev01** [comment]
@climbingdaily If I have only pose and translation for a single person, can I use this tool to visualize it? If yes, how should the .pkl file be configured.

**Comment by cs24m106** [comment]
it doesnt load the sample pkl as well:
```
[entity=89, primitive @ 0] missing required attributes (000000000000000D), declared=0000000000000005
[entity=92, primitive @ 0] missing required attributes (000000000000000D), declared=0000000000000005
[entity=95, primitive @ 0] missing required attributes (000000000000000D), declared=0000000000000005
[entity=98, primitive @ 0] missing required attributes (000000000000000D), declared=0000000000000005
[Open3D INFO] [o3d] name: smpl_sample.pkl.
Unhandled exception caught in c10/util/AbortHandler.h
00007FF8A4C81DD400007FF8A4C79540 torch_python.dll!torch::autograd::THPCppFunction_requires_grad [<unknown file> @ <unknown line number>]
00007FFA852A19D700007FFA852A19C0 ucrtbase.dll!terminate [<unknown file> @ <unknown line number>]
00007FF75E7619D2 <unknown symbol address> python.exe!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFA85DF570300007FFA85DF5510 KERNELBASE.dll!UnhandledExceptionFilter [<unknown file> @ <unknown line number>]
00007FFA884A010800007FFA8849F6B0 ntdll.dll!RtlEncodeRemotePointer [<unknown file> @ <unknown line number>]
00007FFA884A5A2000007FFA884A5970 ntdll.dll!KiUserApcDispatcher [<unknown file> @ <unknown line number>]
00007FFA884A61CF00007FFA884A6130 ntdll.dll!_chkstk [<unknown file> @ <unknown line number>]
00007FFA883523A700007FFA88351E10 ntdll.dll!RtlLocateExtendedFeature [<unknown file> @ <unknown line number>]
00007FFA8834A96100007FFA8834A740 ntdll.dll!RtlRaiseException [<unknown file> @ <unknown line number>]
00007FFA85DA73FA00007FFA85DA7370 KERNELBASE.dll!RaiseException [<unknown file> @ <unknown line number>]
00007FF8312859A000007FF82F7E2F80 pybind.cp312-win_amd64.pyd!librealsense::get_string [<unknown file> @ <unknown line number>]
00007FF82E9158B200007FF82E87D940 pybind.cp312-win_amd64.pyd!librealsense::color_map::get_cache [<unknown file> @ <unknown line number>]
00007FF82EC7629E00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC5BC2B00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC651EA00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC651EA00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC651EA00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC4D94C00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC4E06300007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC4E84100007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82F477A8A00007FF82F35C930 pybind.cp312-win_amd64.pyd!librealsense::frame_holder::frame_holder [<unknown file> @ <unknown line number>]
00007FFA862EC39600007FFA862EBCF0 USER32.dll!CallWindowProcW [<unknown file> @ <unknown line number>]
00007FFA862EBE5C00007FFA862EBCF0 USER32.dll!CallWindowProcW [<unknown file> @ <unknown line number>]
00007FFA5F04BE1300007FFA5F04AB50 OPENGL32.dll!wglSwapLayerBuffers [<unknown file> @ <unknown line number>]
00007FFA862EC39600007FFA862EBCF0 USER32.dll!CallWindowProcW [<unknown file> @ <unknown line number>]
00007FFA862EBC1C00007FFA862EB150 USER32.dll!SendMessageW [<unknown file> @ <unknown line number>]
00007FFA86322CE300007FFA86322810 USER32.dll!GetWindowDpiAwarenessContext [<unknown file> @ <unknown line number>]
00007FFA884A5AB400007FFA884A5A90 ntdll.dll!KiUserCallbackDispatcher [<unknown file> @ <unknown line number>]
00007FFA84FDCA5400007FFA84FDCA40 win32u.dll!NtUserUpdateWindow [<unknown file> @ <unknown line number>]
00007FF82EC4F10000007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EEE878900007FF82ECEEE90 pybind.cp312-win_amd64.pyd!librealsense::option_range::operator= [<unknown file> @ <unknown line number>]
00007FF82F47809B00007FF82F35C930 pybind.cp312-win_amd64.pyd!librealsense::frame_holder::frame_holder [<unknown file> @ <unknown line number>]
00007FFA862EC39600007FFA862EBCF0 USER32.dll!CallWindowProcW [<unknown file> @ <unknown line number>]
00007FFA862EBE5C00007FFA862EBCF0 USER32.dll!CallWindowProcW [<unknown file> @ <unknown line number>]
00007FFA5F04BE1300007FFA5F04AB50 OPENGL32.dll!wglSwapLayerBuffers [<unknown file> @ <unknown line number>]
00007FFA862EC39600007FFA862EBCF0 USER32.dll!CallWindowProcW [<unknown file> @ <unknown line number>]
00007FFA862EA7ED00007FFA862EA420 USER32.dll!IsWindowUnicode [<unknown file> @ <unknown line number>]
00007FF82F47504B00007FF82F35C930 pybind.cp312-win_amd64.pyd!librealsense::frame_holder::frame_holder [<unknown file> @ <unknown line number>]
00007FF82EEE8B6B00007FF82ECEEE90 pybind.cp312-win_amd64.pyd!librealsense::option_range::operator= [<unknown file> @ <unknown line number>]
00007FF82EC6CB6900007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82EC6D95C00007FF82EA974B0 pybind.cp312-win_amd64.pyd!librealsense::option::is_read_only [<unknown file> @ <unknown line number>]
00007FF82E9097CC00007FF82E87D940 pybind.cp312-win_amd64.pyd!librealsense::color_map::get_cache [<unknown file> @ <unknown line number>]
00007FF82E8F113B00007FF82E87D940 pybind.cp312-win_amd64.pyd!librealsense::color_map::get_cache [<unknown file> @ <unknown line number>]
00007FF82E5E0A1F <unknown symbol address> pybind.cp312-win_amd64.pyd!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FF9FF64A8C400007FF9FF64A74C python312.dll!PyObject_VectorcallMethod [<unknown file> @ <unknown line number>]
00007FF9FF62B71A00007FF9FF62AB90 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF9FF62ABC500007FF9FF62AB90 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF9FF62CA9700007FF9FF62C330 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF9FF644A2200007FF9FF644800 python312.dll!PyMapping_Check [<unknown file> @ <unknown line number>]
00007FF9FF64408100007FF9FF643FD4 python312.dll!PyEval_EvalCode [<unknown file> @ <unknown line number>]
00007FF9FF64218C00007FF9FF64200C python312.dll!PyArena_Free [<unknown file> @ <unknown line number>]
00007FF9FF64210000007FF9FF64200C python312.dll!PyArena_Free [<unknown file> @ <unknown line number>]
00007FF9FF703E9000007FF9FF703D88 python312.dll!PyImport_FixupExtensionObject [<unknown file> @ <unknown line number>]
00007FF9FF703C1A00007FF9FF703AF4 python312.dll!PyRun_SimpleFileObject [<unknown file> @ <unknown line number>]
00007FF9FF70327000007FF9FF70321C python312.dll!PyRun_AnyFileObject [<unknown file> @ <unknown line number>]
00007FF9FF7030AE00007FF9FF7028BC python312.dll!PyFile_GetLine [<unknown file> @ <unknown line number>]
00007FF9FF702F8B00007FF9FF7028BC python312.dll!PyFile_GetLine [<unknown file> @ <unknown line number>]
00007FF9FF69876E00007FF9FF6983F0 python312.dll!Py_RunMain [<unknown file> @ <unknown line number>]
00007FF9FF69840500007FF9FF6983F0 python312.dll!Py_RunMain [<unknown file> @ <unknown line number>]
00007FF9FF5F484500007FF9FF5F4820 python312.dll!Py_Main [<unknown file> @ <unknown line number>]
00007FF75E761230 <unknown symbol address> python.exe!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFA87A3E8D700007FFA87A3E8C0 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFA883CC48C00007FFA883CC460 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]
```
any idea how to resolve this error?
